### ISSUE TITLE
Remove sfixed in \DeclareFontShape

### ISSUE THREAD

**Issue by RuixiZhang42** [TeX-Live/yhmath#2]
Please make `yhcmex10` scalable by using the following font definition:

```tex
\ProvidesFile{OMXyhex.fd}
          [2013/07/03 v1.1 YH's humble contribution to TeX maths (NP)]% May need to change as well
\DeclareFontFamily{OMX}{yhex}{}
\DeclareFontShape{OMX}{yhex}{m}{n}{
   <->yhcmex10% Remove sfixed
   }{}
```

Fixing extensible font at only one size leads to ugly outputs. See

- https://tex.stackexchange.com/a/137143
- https://tex.stackexchange.com/a/186356
- https://tex.stackexchange.com/a/219357
- https://tex.stackexchange.com/a/376031

**Comment by RuixiZhang42** [comment]
Oh, and here is another post from 2018/01/01 suggesting to remove `sfixed`:

- https://tex.stackexchange.com/a/408360

and it addresses directly to `yhcmex10`.

**Comment by norbusan** [comment]
Thanks, will do this weekend

**Comment by norbusan** [comment]
Thanks, I have committed this and the other change, but I want to compare the outputs of the examples from the tex.sx sites you linked to, to see whether it is an actual change and/or improvement.

**Comment by norbusan** [comment]
Hmmm, when I use the document
```
\documentclass[11pt]{article}
%
\usepackage{amsmath}
%
\makeatletter
%
\usepackage{yhmath}
\usepackage{lipsum}
%
\makeatother
%
\begin{document}
%
\lipsum[1]
\begin{equation}
2^k-\binom{k}{1}2^{k-1}+\binom{k}{2}2^{k-2}
\end{equation}
\lipsum[1]
%
\end{document}
```
I think the one **with** sfixed actually looks better, because the paranthesis of the binom are extended less above the k.

Can you check this, too?

**Comment by RuixiZhang42** [comment]
Thanks for the prompt response!

I have the following MWE to test with:

```tex
\documentclass[fontsize=20pt]{scrbook}
\usepackage{yhmath}
%\DeclareFontFamily{OMX}{yhex}{}
%\DeclareFontShape{OMX}{yhex}{m}{n}{
%   <->yhcmex10% Remove sfixed
%   }{}
\begin{document}
\[
\text{20pt text: } \sqrt{\frac{m}{n}}
\]
\end{document}
```

Here is the output with **fixed-size** `yhcmex10`:

> ![a1](https://user-images.githubusercontent.com/39968857/53282029-18f8d880-3700-11e9-8698-ae0860091f91.png)

And here is the one with **scalable** `yhcmex10`:

> ![a2](https://user-images.githubusercontent.com/39968857/53282033-2e6e0280-3700-11e9-9b2f-02e6a89690d1.png)

---

For comparison, this is the output for a “normal” 10pt article:

> ![a3](https://user-images.githubusercontent.com/39968857/53282041-49407700-3700-11e9-97a9-a7274957767c.png)

**Comment by RuixiZhang42** [comment]
The thing is, `yhmath` has different parentheses than the default Computer Modern. I&nbsp;suspect that the “larger parentheses” come from some of those “intermediate sizes”. So in a 10pt article, `yhmath` produces slightly larger parentheses anyway.

Indeed, it is possible that without `yhmath`, TeX can only choose between `\bigg` and `\Bigg` and it settles down with `\bigg`, but now `yhmath` provides something in the middle so it choose the intermediate ones. My next example supports this observation:

```tex
\documentclass[10pt]{article}
\usepackage{amsmath}
%\usepackage{yhmath}
\usepackage{lipsum}
\begin{document}
\lipsum[1]
\begin{equation}
2^k-\biggl(\Biggl(\binom{n}{1}2^{k-1}+\binom{n}{2}2^{k-2}
\end{equation}
\lipsum[1]
\end{document}
```

---

With the default Computer Modern (no `yhmath`):

> ![a4](https://user-images.githubusercontent.com/39968857/53282368-b2c28480-3704-11e9-9eac-469aae3d8bc0.png)


---

Using `yhmath` (either fixed or scalable is irrelevant here as the above MWE is in 10pt):

> ![a5](https://user-images.githubusercontent.com/39968857/53282373-ba822900-3704-11e9-8f49-a2fc8bc94981.png)


---

So, in your test 11pt article, since the parentheses are fixed at 10pt design size but the letters are now in 10.95pt, it creates the illusion that “parentheses are just right”.

**Comment by RuixiZhang42** [comment]
IMHO, it is not the font’s fault that TeX chooses the slightly larger intermediate size. If we pinned `yhcmex10` to only one size, then it would destroy `\sqrt` *for sure* (it was too close to its content, its rules were too thin and its slope and proportion were off in my 20pt example).

If the user find the parentheses given by `\binom` are too large, they can always redefine `\binom` like this:

```tex
\documentclass[10pt]{article}
\usepackage{lipsum}
\usepackage{amsmath}
\usepackage{yhmath}
\DeclareFontFamily{OMX}{yhex}{}
\DeclareFontShape{OMX}{yhex}{m}{n}{
   <->yhcmex10% Remove sfixed
   }{}
\DeclareRobustCommand{\binom}[2]{%
  \left(%
    \kern-\nulldelimiterspace
    \genfrac{}{}{0pt}{}{\mathstrut#1}{\mathstrut#2}%
    \kern-\nulldelimiterspace
  \right)%
}
\begin{document}
\lipsum[1]
\begin{equation}
2^k-\biggl(\Biggl(\binom{k}{1}2^{k-1}+\binom{n}{2}2^{k-2}
\end{equation}
\lipsum[1]
\end{document}
```

---

Use `yhmath` + scalable `yhcmex10` + redefined `\binom`:

> ![a6](https://user-images.githubusercontent.com/39968857/53287757-ce527d00-374e-11e9-8333-49d0bb9bbf77.png)

---

Again, with the default (no `yhmath` and no redefinition):

> ![a7](https://user-images.githubusercontent.com/39968857/53287789-4a4cc500-374f-11e9-9173-a2e3a816c41b.png)

We can see that `yhcmex10`’s `\bigg` is slightly smaller than `cmex10`’s `\bigg`, but is fine to be used in `\binom`. I&nbsp;also find the intermediate size acceptable but that’s my personal taste.

**Comment by norbusan** [comment]
v1.5 released with the respective change
