### ISSUE TITLE
Command \widering already defined

### ISSUE THREAD

**Issue by ivankokan** [TeX-Live/yhmath#4]
Hi, Here is another issue in which I get
```
! LaTeX Error: Command \widering already defined.
               Or name \end... illegal, see p.192 of the manual.

```
irrelevant to whether the new option `nowidering` is being used or not.

MWE:
```
\documentclass{article}

\usepackage{newtxtext}
\usepackage{newtxmath}

\usepackage{amsmath}
\usepackage{amssymb}

\usepackage[nowidering]{yhmath}


\begin{document}
  \[ \widearc{AB} \wideparen{AB} \]
\end{document}
```

**Comment by RuixiZhang42** [comment]
`newtxmath` and `amssymb` are incompatible, which means `newtxmath` and `yhmath` are incompatible as well. You use the former if you want Times-like font for math, and the latter if you want the good old Computer Modern Roman. These two families of fonts don’t go together.

**Comment by ivankokan** [comment]
I agree with you, but still... The option `nowidering` should do its work, i.e. undefine previously defined `\widering` to avoid the conflict with some others that define the same command (either before or after `yhmath`, even using hooks).

In given MWE the problem comes from some `\widering` defined earlier (`newtxmath`) than with `yhmath`: so actually
https://github.com/TeX-Live/yhmath/blob/master/yhmath.dtx#L361
does its work (PDF is eventually produced), but the error occured a bit earlier: https://github.com/TeX-Live/yhmath/blob/master/yhmath.dtx#L341. The following order resolves the particular issue:
```
\usepackage{newtxtext}
\usepackage[nowidering]{yhmath}
\usepackage{newtxmath}
\usepackage{amsmath}
\usepackage{amssymb}
```

Let me propose a bit different approach: introducing `widering` *instead* of having `nowidering` option, i.e. defining `\widering` in `yhmath` only if explicitly requested in option list. This way the relative position of `yhmath` would not be important. What do you think?

**Comment by norbusan** [comment]
Hi
If you load yhmath first, then it will work.
Anyway, I will change the loading mechanism that this shouldn't happen.
Thanks

Norbert

**Comment by samestep** [comment]
I still get this issue when trying to use the `yhmath` package to get the `\wideparen` command in the `acmart` document class. Here is the [solution][texfaq] that worked for me:
```latex
\usepackage{savesym}
\savesymbol{widering}
\usepackage{yhmath}
```

[texfaq]: https://texfaq.org/FAQ-alreadydef

**Comment by ivankokan** [comment]
Hi @samestep. Fix was implemented (check commit above), but not released.

**Comment by ivankokan** [comment]
Anyway, any plans for releasing this?

**Comment by norbusan** [comment]
I uploaded 1.6 with the widering fix just now to CTAN.
