### ISSUE TITLE
"already defined" errors

### ISSUE THREAD

**Issue by wujastyk** [TeX-Live/yhmath#6]
Dear Norbert,

I am typesetting an article by a colleague who uses yhmath.  I am getting these "already defined" errors:
 
![image](https://user-images.githubusercontent.com/762246/104763300-e35d9e00-5722-11eb-975c-2ccd63d438c9.png)

His article loads various AMS files, and I expect this is where the first def is happening. 

I attach the log file in case it helps, but the article is ferocious and loads many, many styles.  Getting a MWE is probably impossible.

Best,
Dominik

[persian-astronomy.log](https://github.com/TeX-Live/yhmath/files/5822260/persian-astronomy.log)

**Comment by norbusan** [comment]
HI Dominik,
Yes yhmath cannot be used with all other packages, but you can pass the option `minimal` to the loading of `yhmath`, that should fix the errors.

**Comment by wujastyk** [comment]
Aha.  Thank you, Norbert.

**Comment by norbusan** [comment]
Please let me know if that fixed your issue, so that we can close this one here or something else is needed.

**Comment by wujastyk** [comment]
Yes, I confirm that [minimal] fixed the issue.  Many thanks!
